spring:
  application:
    name: pan-zuul
server:
  port: 7001
eureka:
  client:
    serviceUrl:
       defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
zuul:
  routes:
    user-auth:
      path: /sso/**
      serviceId: pan-sso